export type EventItem = {
  id: number;
  title: string;
  type: string;
  location: string;
  city: string;
  date: string;
  price: string;
  lat: number;
  lng: number;
  description?: string;
};

export const events: EventItem[] = [
  {
    id: 1,
    title: "Desert Night Concert",
    type: "Concert",
    location: "Tempe Beach Park",
    city: "Tempe, AZ",
    date: "May 12",
    price: "$35",
    lat: 33.4308,
    lng: -111.94,
    description: "An outdoor music night with live performances, food stalls, and a premium desert atmosphere.",
  },
  {
    id: 2,
    title: "AI Builders Conference",
    type: "Conference",
    location: "ASU Memorial Union",
    city: "Tempe, AZ",
    date: "May 18",
    price: "$20",
    lat: 33.4172,
    lng: -111.9341,
    description: "A conference for students, founders, and developers interested in AI, startups, and modern software.",
  },
  {
    id: 3,
    title: "Comedy Live Show",
    type: "Shows",
    location: "Downtown Phoenix",
    city: "Phoenix, AZ",
    date: "May 22",
    price: "$25",
    lat: 33.4484,
    lng: -112.074,
    description: "A live comedy show featuring local performers and a relaxed evening crowd.",
  },
  {
    id: 4,
    title: "Startup Workshop",
    type: "Workshop",
    location: "Skysong Innovation Center",
    city: "Scottsdale, AZ",
    date: "May 25",
    price: "Free",
    lat: 33.4636,
    lng: -111.9267,
    description: "A practical workshop for early-stage builders covering product ideas, pitching, and MVP planning.",
  },
  {
    id: 5,
    title: "Luxury Jazz Evening",
    type: "Concert",
    location: "Scottsdale Center",
    city: "Scottsdale, AZ",
    date: "June 2",
    price: "$45",
    lat: 33.4936,
    lng: -111.9261,
    description: "A premium jazz night with elegant seating, live musicians, and a refined lounge atmosphere.",
  },
  {
    id: 6,
    title: "Tech Leadership Summit",
    type: "Conference",
    location: "Phoenix Convention Center",
    city: "Phoenix, AZ",
    date: "June 8",
    price: "$60",
    lat: 33.4483,
    lng: -112.0718,
    description: "A professional summit for technology leaders, builders, founders, and industry speakers.",
  },
  {
    id: 7,
    title: "Hollywood Bowl Summer Night",
    type: "Concert",
    location: "Hollywood Bowl",
    city: "Los Angeles, CA",
    date: "June 14",
    price: "$55",
    lat: 34.1122,
    lng: -118.3388,
    description: "An iconic open-air concert at the legendary Hollywood Bowl with world-class performances under the stars.",
  },
  {
    id: 8,
    title: "Silicon Beach Hackathon",
    type: "Workshop",
    location: "Venice Beach Coworking",
    city: "Los Angeles, CA",
    date: "June 20",
    price: "Free",
    lat: 33.9902,
    lng: -118.4695,
    description: "48-hour hackathon for builders, designers, and founders focused on AI-driven web3 applications.",
  },
  {
    id: 9,
    title: "Brooklyn Jazz Festival",
    type: "Concert",
    location: "Prospect Park Bandshell",
    city: "New York City, NY",
    date: "June 21",
    price: "$40",
    lat: 40.6602,
    lng: -73.9690,
    description: "An annual outdoor jazz festival celebrating the best of contemporary and classic jazz in Brooklyn.",
  },
  {
    id: 10,
    title: "NYC Founders Conference",
    type: "Conference",
    location: "Javits Center",
    city: "New York City, NY",
    date: "June 28",
    price: "$75",
    lat: 40.7573,
    lng: -74.0021,
    description: "New York's largest gathering of startup founders, venture capitalists, and product leaders.",
  },
  {
    id: 11,
    title: "South by Southwest Workshop",
    type: "Workshop",
    location: "Austin Convention Center",
    city: "Austin, TX",
    date: "July 5",
    price: "$30",
    lat: 30.2627,
    lng: -97.7403,
    description: "Creative and tech workshops spanning music, film, interactive media, and entrepreneurship.",
  },
  {
    id: 12,
    title: "Houston Rodeo Concert",
    type: "Concert",
    location: "NRG Stadium",
    city: "Houston, TX",
    date: "July 12",
    price: "$50",
    lat: 29.6847,
    lng: -95.4107,
    description: "Country and pop superstars headline this iconic Texas event blending rodeo tradition with live music.",
  },
  {
    id: 13,
    title: "Lollapalooza Aftershow",
    type: "Concert",
    location: "Metro Chicago",
    city: "Chicago, IL",
    date: "July 18",
    price: "$35",
    lat: 41.9476,
    lng: -87.6500,
    description: "Official Lollapalooza aftershow featuring indie rock, electronic, and hip-hop acts in an intimate venue.",
  },
  {
    id: 14,
    title: "Miami Design Workshop",
    type: "Workshop",
    location: "Wynwood Arts District",
    city: "Miami, FL",
    date: "July 25",
    price: "Free",
    lat: 25.8007,
    lng: -80.1987,
    description: "Hands-on design sprint for product designers and creatives inside Miami's famous Wynwood arts hub.",
  },
  {
    id: 15,
    title: "Orlando Live Comedy",
    type: "Shows",
    location: "Hard Rock Live Orlando",
    city: "Orlando, FL",
    date: "August 2",
    price: "$30",
    lat: 28.5383,
    lng: -81.4033,
    description: "Stand-up and improv comedy showcasing Florida's funniest local and touring comedians.",
  },
  {
    id: 16,
    title: "Atlanta Hip-Hop Summit",
    type: "Conference",
    location: "State Farm Arena",
    city: "Atlanta, GA",
    date: "August 9",
    price: "$45",
    lat: 33.7573,
    lng: -84.3963,
    description: "The Southeast's premier hip-hop industry event with panels, performances, and artist showcases.",
  },
  {
    id: 17,
    title: "Seattle Indie Film Festival",
    type: "Shows",
    location: "SIFF Cinema Uptown",
    city: "Seattle, WA",
    date: "August 15",
    price: "$20",
    lat: 47.6254,
    lng: -122.3517,
    description: "A week-long showcase of independent films from Pacific Northwest and international filmmakers.",
  },
  {
    id: 18,
    title: "Denver Startup Weekend",
    type: "Workshop",
    location: "Galvanize Denver",
    city: "Denver, CO",
    date: "August 22",
    price: "Free",
    lat: 39.7392,
    lng: -104.9847,
    description: "54-hour startup sprint where teams build products, pitch to investors, and compete for prizes.",
  },
];
