export type Showtime = { time: string; format: string; available: boolean };

export type Movie = {
  id: number;
  title: string;
  genre: string[];
  rating: string;
  duration: string;
  year: number;
  director: string;
  description: string;
  trailerYoutubeId: string;
  price: string;
  theater: string;
  city: string;
  state: string;
  showtimes: Showtime[];
};

export const movies: Movie[] = [
  {
    id: 101,
    title: "Dune: Part Two",
    genre: ["Sci-Fi", "Adventure"],
    rating: "PG-13",
    duration: "2h 46m",
    year: 2024,
    director: "Denis Villeneuve",
    description: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against those who destroyed his family, as dark forces brew.",
    trailerYoutubeId: "Way9Dexny3w",
    price: "$18",
    theater: "AMC Tempe Marketplace 16",
    city: "Tempe",
    state: "AZ",
    showtimes: [
      { time: "10:30 AM", format: "IMAX", available: true },
      { time: "1:45 PM", format: "Standard", available: true },
      { time: "5:00 PM", format: "IMAX", available: true },
      { time: "8:15 PM", format: "Dolby", available: false },
    ],
  },
  {
    id: 102,
    title: "Oppenheimer",
    genre: ["Drama", "History", "Thriller"],
    rating: "R",
    duration: "3h 0m",
    year: 2023,
    director: "Christopher Nolan",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during WWII.",
    trailerYoutubeId: "uYPbbksJxIg",
    price: "$16",
    theater: "Regal LA Live",
    city: "Los Angeles",
    state: "CA",
    showtimes: [
      { time: "11:00 AM", format: "Standard", available: true },
      { time: "2:30 PM", format: "IMAX", available: true },
      { time: "6:00 PM", format: "IMAX", available: false },
      { time: "9:30 PM", format: "Standard", available: true },
    ],
  },
  {
    id: 103,
    title: "The Batman",
    genre: ["Action", "Crime", "Drama"],
    rating: "PG-13",
    duration: "2h 56m",
    year: 2022,
    director: "Matt Reeves",
    description: "Batman ventures into Gotham City's underworld when a sadistic killer leaves behind a series of cryptic clues.",
    trailerYoutubeId: "mqqft2x_Aa4",
    price: "$15",
    theater: "AMC Empire 25",
    city: "New York City",
    state: "NY",
    showtimes: [
      { time: "12:00 PM", format: "Standard", available: true },
      { time: "3:15 PM", format: "Dolby", available: true },
      { time: "6:30 PM", format: "Standard", available: true },
      { time: "9:45 PM", format: "Dolby", available: false },
    ],
  },
  {
    id: 104,
    title: "Top Gun: Maverick",
    genre: ["Action", "Drama"],
    rating: "PG-13",
    duration: "2h 11m",
    year: 2022,
    director: "Joseph Kosinski",
    description: "After 30 years, Maverick is still pushing the envelope as a top naval aviator, but he must confront the ghosts of his past.",
    trailerYoutubeId: "giXco2jaZ_4",
    price: "$17",
    theater: "AMC Dine-In Houston 8",
    city: "Houston",
    state: "TX",
    showtimes: [
      { time: "11:30 AM", format: "Standard", available: true },
      { time: "2:00 PM", format: "IMAX", available: false },
      { time: "4:45 PM", format: "Standard", available: true },
      { time: "7:30 PM", format: "IMAX", available: true },
    ],
  },
  {
    id: 105,
    title: "Interstellar",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    rating: "PG-13",
    duration: "2h 49m",
    year: 2014,
    director: "Christopher Nolan",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival as Earth faces collapse.",
    trailerYoutubeId: "zSWdZVtXT7E",
    price: "$14",
    theater: "Music Box Theatre",
    city: "Chicago",
    state: "IL",
    showtimes: [
      { time: "1:00 PM", format: "70mm Film", available: true },
      { time: "4:30 PM", format: "IMAX", available: true },
      { time: "8:00 PM", format: "70mm Film", available: true },
    ],
  },
  {
    id: 106,
    title: "Spider-Man: No Way Home",
    genre: ["Action", "Sci-Fi", "Adventure"],
    rating: "PG-13",
    duration: "2h 28m",
    year: 2021,
    director: "Jon Watts",
    description: "Spider-Man seeks help from Doctor Strange to restore his secret identity, but things go catastrophically wrong.",
    trailerYoutubeId: "JfVOs4VSpmA",
    price: "$16",
    theater: "Regal South Beach",
    city: "Miami",
    state: "FL",
    showtimes: [
      { time: "10:00 AM", format: "Standard", available: true },
      { time: "1:00 PM", format: "4DX", available: true },
      { time: "4:00 PM", format: "Standard", available: false },
      { time: "7:00 PM", format: "4DX", available: true },
      { time: "10:00 PM", format: "Standard", available: true },
    ],
  },
  {
    id: 107,
    title: "Everything Everywhere All at Once",
    genre: ["Sci-Fi", "Comedy", "Action"],
    rating: "R",
    duration: "2h 19m",
    year: 2022,
    director: "Daniel Kwan & Daniel Scheinert",
    description: "A middle-aged Chinese immigrant is swept up in an outlandish adventure where she alone can save the multiverse.",
    trailerYoutubeId: "wxN1T1uxQ2g",
    price: "$13",
    theater: "SIFF Cinema Uptown",
    city: "Seattle",
    state: "WA",
    showtimes: [
      { time: "12:30 PM", format: "Standard", available: true },
      { time: "3:30 PM", format: "Standard", available: true },
      { time: "6:30 PM", format: "Standard", available: false },
      { time: "9:15 PM", format: "Standard", available: true },
    ],
  },
  {
    id: 108,
    title: "Poor Things",
    genre: ["Comedy", "Drama", "Romance"],
    rating: "R",
    duration: "2h 21m",
    year: 2023,
    director: "Yorgos Lanthimos",
    description: "The story of the incredible development of Bella Baxter, a young woman brought back to life by an eccentric scientist.",
    trailerYoutubeId: "RlbR5N6veqw",
    price: "$15",
    theater: "Landmark Shattuck Cinemas",
    city: "San Francisco",
    state: "CA",
    showtimes: [
      { time: "2:00 PM", format: "Standard", available: true },
      { time: "5:15 PM", format: "Standard", available: true },
      { time: "8:30 PM", format: "Standard", available: false },
    ],
  },
  {
    id: 109,
    title: "Tenet",
    genre: ["Action", "Sci-Fi", "Thriller"],
    rating: "PG-13",
    duration: "2h 30m",
    year: 2020,
    director: "Christopher Nolan",
    description: "Armed with only one word, Tenet, and fighting for the survival of the entire world, a Protagonist journeys through a twilight world of international espionage.",
    trailerYoutubeId: "LdOM0x0XDMo",
    price: "$14",
    theater: "Alamo Drafthouse Denver",
    city: "Denver",
    state: "CO",
    showtimes: [
      { time: "1:15 PM", format: "IMAX", available: true },
      { time: "4:30 PM", format: "Standard", available: true },
      { time: "7:45 PM", format: "IMAX", available: true },
    ],
  },
  {
    id: 110,
    title: "The Dark Knight",
    genre: ["Action", "Crime", "Drama"],
    rating: "PG-13",
    duration: "2h 32m",
    year: 2008,
    director: "Christopher Nolan",
    description: "The Joker wreaks havoc on Gotham City in this acclaimed superhero thriller featuring Heath Ledger's legendary performance.",
    trailerYoutubeId: "EXeTwQWrcwY",
    price: "$12",
    theater: "AMC Boston Common 19",
    city: "Boston",
    state: "MA",
    showtimes: [
      { time: "11:00 AM", format: "Standard", available: true },
      { time: "2:30 PM", format: "IMAX", available: false },
      { time: "6:00 PM", format: "Standard", available: true },
      { time: "9:30 PM", format: "IMAX", available: true },
    ],
  },
  {
    id: 111,
    title: "Avatar: The Way of Water",
    genre: ["Sci-Fi", "Adventure", "Action"],
    rating: "PG-13",
    duration: "3h 12m",
    year: 2022,
    director: "James Cameron",
    description: "Jake Sully and Ney'tiri have formed a family and are doing everything to stay together. However, they must leave their home and explore the regions of Pandora.",
    trailerYoutubeId: "d9MyW72ELq0",
    price: "$19",
    theater: "Regal Las Vegas",
    city: "Las Vegas",
    state: "NV",
    showtimes: [
      { time: "10:00 AM", format: "3D IMAX", available: true },
      { time: "1:30 PM", format: "3D", available: true },
      { time: "5:00 PM", format: "3D IMAX", available: false },
      { time: "8:30 PM", format: "3D", available: true },
    ],
  },
  {
    id: 112,
    title: "Black Panther: Wakanda Forever",
    genre: ["Action", "Adventure", "Drama"],
    rating: "PG-13",
    duration: "2h 41m",
    year: 2022,
    director: "Ryan Coogler",
    description: "The people of Wakanda fight to protect their home from intervening world powers as they mourn the death of King T'Challa.",
    trailerYoutubeId: "_Z3QKkl1WyM",
    price: "$16",
    theater: "Regal Phipps Plaza",
    city: "Atlanta",
    state: "GA",
    showtimes: [
      { time: "12:00 PM", format: "Standard", available: true },
      { time: "3:00 PM", format: "Dolby", available: true },
      { time: "6:00 PM", format: "Standard", available: true },
      { time: "9:00 PM", format: "Dolby", available: false },
    ],
  },
];

export function getMovieById(id: number): Movie | undefined {
  return movies.find((m) => m.id === id);
}
